# Start your image with an ubuntu base image
FROM ubuntu:latest

# Update packages
RUN apt-get update \
&& apt-get upgrade -y

# Display "Hello, World!" when the container runs
CMD ["echo", "Hello, World!"]
